### ISSUE TITLE
has no exported member 'Observable'

### ISSUE THREAD

**Issue by chinha0** [DethAriel/ng-recaptcha#115]
### Summary

I'm submitting a: 
- [x ] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

After I had finish npm install and import the required modules for the recaptcha. I faced this error:

ERROR in node_modules/ng-recaptcha/recaptcha/recaptcha-loader.service.d.ts(3,10): error TS2305: Module '"C:/Users/neave/Desktop/RUYI_Portal/FormsSubmit/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by codebubb** [comment]
Hi, I came across this issue whilst trying to incorporate in an Angular 6 project.  

It looks like it's down to the way that imports have changed in RxJS 6.  I sorted the problem (temporarily) by changing the import on line 3 of the `recaptcha-loader.service.d.ts` file from:

```
import { Observable } from 'rxjs/Observable';
```
to:
```
import { Observable } from 'rxjs';
```

Which is now the required way to import Observable.

**Comment by devMagics** [comment]
+1

**Comment by Whamo12** [comment]
This error is due to RxJS 6 now being a mandatory dependency for Angular 6.  RxJS 6 has breaking changes which include:

1. Modified internal structure that requires changing import statements
2. `pipe()` is now used to chain operators

A quick workaround to fix this issue is to add the `rxjs-compat` library which will allow backward-compatibility.

`npm install --save rxjs-compat`

**Comment by DethAriel** [comment]
Folks, a stable 4.0.0 has been released now, so feel free to upgrade! It should resolve the RxJS 6 error message
