### ISSUE TITLE
ERROR in There is no format with import statements in 'path-to-local-node-modules/node_modules/ng-recaptcha' entry-point

### ISSUE THREAD

**Issue by bunnyvishal6** [DethAriel/ng-recaptcha#141]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

While using angular 8 + Ivy preview getting this error
ERROR in There is no format with import statements in 'path-to-local-node-modules/node_modules/ng-recaptcha' entry-point.

Lib versions:
* ng-recaptcha: 4.2.1
* Angular: 8.0.0
* Typescript (`tsc --version`): 3.4.5

**Comment by plchampigny** [comment]
Got the same issue

**Comment by DethAriel** [comment]
@bunnyvishal6 thx for submitting this! @plchampigny this is definitely a good suggestion.

I'll try to get to fixing this by the end of this week (Friday, most likely).

**Comment by marvinrusinek** [comment]
I'm also getting the same error message for ng-recaptcha after enabling Ivy and running ng serve.

**Comment by DethAriel** [comment]
Hey folks! Friday has come and gone, and I’m just letting you know that I’m still working on this (trying to understand the potential breaking changes for SystemJS users). I’ll give an update next Tuesday

**Comment by DethAriel** [comment]
So it's Tuesday, and I'm happy to announce that support for Angular 8 as a peer dependency has been added in v5.0.0-beta.1. This is a breaking change, since there's also a shift to ng-packagr for bundle management, which should solve the issues you were seeing with Ivy. Please try it out and let me know if you spot any issues.

Thx for bearing with me on that!

**Comment by marvinrusinek** [comment]
I installed ng-recaptcha@v5.0.0-beta.1 but now I'm getting errors now for other node modules like: 
ERROR in There is no format with import statements in 'path/node_modules/ngx-lazy-load-images' entry-point.
Tried removing it since I wasn't using it and then getting other format error messages for other node modules. What should I do to fix this issue?

**Comment by DethAriel** [comment]
@marvinrusinek you should contact the authors of the other libraries and submit an issue similar to this one, but against their respective libs

**Comment by ratkovicnikola** [comment]
Maybe I'm doing something wrong, but when I install this v.5.0.0-beta.1 I'm getting error message in my app.module -> `Cannot find module 'ng-recaptcha'.`

**Comment by bunnyvishal6** [comment]
@ratkovicnikola  try this
```
import {  } from 'ng-recaptcha/dist'
```

**Comment by nrone** [comment]
I get the same issue, Cannot find module 'ng-recaptcha'. And import { RecaptchaComponent } from 'ng-recaptcha/dist' does say the same for me.

**Comment by DethAriel** [comment]
Hey 👋 
Let me find out what’s going on, I’ll get back to you folks in a couple hours. There has been an issue previously when the module publishing didn’t quite work as it should have, so I’m wondering if I made the same mistake again... Apologies for that in advance

**Comment by DethAriel** [comment]
Yes, the module indeed was published wrongly. I've re-published this as v5.0.0-beta.2 and deprecated v5.0.0-beta.1

**Comment by DethAriel** [comment]
v5 is out of beta, so I'm marking this issue as closed
