### ISSUE TITLE
Support for Angular 8

### ISSUE THREAD

**Issue by icecoldfire** [DethAriel/ng-recaptcha#142]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

npm WARN ng-recaptcha@4.2.1 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

### Demo
Upgrade to angular 8 using https://update.angular.io/#7.0:8.0

Lib versions:

* ng-recaptcha: 4.2.1
* Angular: 8.0.0
* Typescript (`tsc --version`): 3.4.5

**Comment by DethAriel** [comment]
support for Angular 8 as a peer dependency has been added in v5.0.0-beta.1. This will be a breaking change, since there's also a shift to `ng-packagr` for bundle management.

**Comment by jjzjx118** [comment]
so it's not supporting Angular 8 with the version of 4.3.0 ?

**Comment by DethAriel** [comment]
@jjzjx118 unfortunately, no - as outlined [in the changelog](https://github.com/DethAriel/ng-recaptcha/blob/vnext/CHANGELOG.md#500-beta1-2019-06-04), there were some breaking changes to ensure compatibility with Ivy, so that had to be a major release. The good news is - there's a pretty good chance that you won't have to change any of your code as part of that upgrade, so it should be fairly straightforward

**Comment by MicMicMon** [comment]
Any visibility on when the package would be out of beta?
Thanks for all the great work!

**Comment by Hugoer** [comment]
Thank you very much for your work! Do you have any forecast for Angular 8?

**Comment by danieldanielecki** [comment]
+1

**Comment by aviaur** [comment]
+1

**Comment by vrossini** [comment]
+1

**Comment by DethAriel** [comment]
Hey all! Sorry for making you wait for so long, summer has been quite busy. v5 is out of beta, and you can use it today! FYI, there have been no changes since `v5.0.0-beta.2`
