### ISSUE TITLE
Why recaptcha.js  downloaded 4 times

### ISSUE THREAD

**Issue by megastas** [DethAriel/ng-recaptcha#146]
<img width="1662" alt="Screenshot 2019-07-23 at 17 30 41" src="https://user-images.githubusercontent.com/5328653/61720773-17dfdc00-ad70-11e9-9a5b-729af901e863.png">

I provided example from here https://dethariel.github.io/ng-recaptcha/, but same for my site. 
Could you please explain why it is? Thanks.

**Comment by megastas** [comment]
And styles__ltr.css 2 times, thank you very much.

**Comment by DethAriel** [comment]
Hi @megastas ! I don't have an answer for you, frankly. The only file that this lib is setting to download is `https://www.google.com/recaptcha/api.js`, which in turn, I suppose, is the one downloading the recaptcha.js file 4 times. The same goes for the CSS file that you mentioned.

Since the same happens without `ng-recaptcha` lib, I consider that to be normal operation of the reCAPTCHA itself, although for a reason that is unknown to me.
