### ISSUE TITLE
Destroy recaptchaV3 manually

### ISSUE THREAD

**Issue by erdenerunl** [DethAriel/ng-recaptcha#220]
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description
I want to add recaptchaV3 on my login modal box form and I want to destroy it manually when my modal component is destroyed. Because i dont need it anymore.

**Comment by DethAriel** [comment]
Hi @erdenerunl and others! Can you help me understand the problem a little bit better? The way I see it, you're trying to achieve one of these two outcomes:

1. No longer have the reCAPTCHA badge being displayed on the screen after the user gets past the login form
2. Completely unload the reCAPTCHA-related javascript from the memory ((since, well, it's no longer needed)

For hiding the badge, there's a section on this in reCAPTCHA FAQ [here](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed), let me provide an excerpt:

> You are allowed to hide the badge as long as you include the reCAPTCHA branding visibly in the user flow. Please include the following text:
>
>
> This site is protected by reCAPTCHA and the Google <a href="https://policies.google.com/privacy">Privacy Policy</a> and <a href="https://policies.google.com/terms">Terms of Service</a> apply.

If, on the other hand, you're looking to unload the JS resourced used by reCAPTCHA, I'm afraid I'm not aware of a way to do so in an SPA environment. One way to avoid the JS memory "pollution" of login flows in your application is to de-couple login flow from the rest of your app, but this is, in general, a significant undertaking, and probably not something you're looking for my input on.

I'm not seeing a third option here, and given that `ng-recaptcha` cannot directly address neither 1) nor 2), I'm going to close this bug report. Feel free to re-open if you think I've missed anything. Cheers!
