### ISSUE TITLE
ERROR in node_modules/ng-recaptcha/recaptcha/recaptcha.component.d.ts(5,43): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by erdenerunl** [DethAriel/ng-recaptcha#221]
### Summary

I'm submitting a: 

- [x] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description

I am facing this error on terminal, although it works properly.
```export declare type NeverUndefined<T> = T extends undefined ? never : T;```
This is a line in recaptcha.component.d.ts that gives this error.

Lib versions:

* ng-recaptcha: 7.0.1
* Angular: 5.2.6
* Typescript (`tsc --version`): 2.5.3

**Comment by DethAriel** [comment]
Support for older versions of Angular was discontinued as of version `7.0.0` as per [change log](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md#700-2020-12-22). Angular 5 hasn't been supported since v4.0.0 as per [change log](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md#400-2018-09-29).

You have two options: either staying on ng-recaptcha v3.x.x, or upgrading to a newer version of Angular
