### ISSUE TITLE
ng-recaptcha does not show in angular 10

### ISSUE THREAD

**Issue by lebaphi** [DethAriel/ng-recaptcha#236]
Hi,

This is my libs version:
```
    "@angular/compiler": "^10.2.5",
    "@angular/compiler-cli": "^10.2.5",
    "@angular/core": "^10.2.5",
    "@angular/forms": "^10.2.5",
    "ng-recaptcha": "^8.0.0",
```

app.module.ts
```
import { RecaptchaModule } from 'ng-recaptcha';
....
imports: [
    RecaptchaModule,
]
```

login.component.ts
```
public resolved(captchaResponse: string) {
    console.log(`Resolved captcha with response: ${captchaResponse}`) 
}

public errored() {
    console.warn(`reCAPTCHA error encountered`);
}
```

login.component.html
```
<re-captcha (resolved)="resolved($event)" (error)="errored($event)" errorMode="handled"
      siteKey="xxxxxxxx"></re-captcha>
```

I also add `localhost` in the domain section in the google console

![image](https://user-images.githubusercontent.com/26705621/126583407-3aee2d05-6be5-4993-9a35-02365684fd72.png)

but nothing happens on my login view, I can not see the recaptcha, and nothing in the console. Not sure what do I wrong 🤔

**Comment by DethAriel** [comment]
hi @lebaphi ! as per the [change log](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md), support for multiple versions of Angular has been dropped since v7.0.0. The latest version of `ng-recaptcha` to support Angular 10 is the `6.x.x` branch. So a way forward for you is to either upgrade Angular version in your app (which might be too time consuming), or downgrading to `ng-recaptcha@^6`.
