### ISSUE TITLE
Issue with invalid sitekey

### ISSUE THREAD

**Issue by souravion** [DethAriel/ng-recaptcha#271]
How can I handle error if sitekey is invalid 

Code snippet 

```
this.recaptchaV3Service.execute('myAction').subscribe(
              (token) => {
                console.log('Recaptcha v3 token', token);
              },
              (error) => {
                console.log(`Recaptcha v3 error: see console`);
                console.log(`Recaptcha v3 error:`, error);
              }
            );
```

**Comment by DethAriel** [comment]
Exactly like in the code snippet you provided. An example of such handling is also given on the [website](https://dethariel.github.io/ng-recaptcha/v3) (see `v3.component.ts` tab). 

If you are wonderin if an invalid `siteKey` can be fixed in runtime, then this is not something that can be done right now.
