### ISSUE TITLE
Upgrade to Angular 17?

### ISSUE THREAD

**Issue by medbenmakhlouf** [DethAriel/ng-recaptcha#310]
### Summary

I'm submitting a: 

- [x] bug report
- [x] feature request
- [x] question / support request 
- [x] other

### Description

Angular 17 was released today. Is there any release plan for it ? Thanks

**Comment by medbenmakhlouf** [comment]
I have decided to submit PR to work on the upgrade : https://github.com/DethAriel/ng-recaptcha/pull/311

**Comment by avatier-leonardoc** [comment]
Please merge it. It's critical for my project.

**Comment by vuksamardzic** [comment]
@DethAriel can you take a look at this ?

**Comment by ahocquet** [comment]
@DethAriel I would also be intereted in getting this PR merged :) 🙏

**Comment by alvarolb** [comment]
@DethAriel Just a click for the merge? :) 🙏

**Comment by DethAriel** [comment]
It's not just a click for the merge @alvarolb . Unfortunately, the original PR did not fully follow the contribution guidelines outlined in the [CONTRIBUTING.md](https://github.com/DethAriel/ng-recaptcha/blob/master/CONTRIBUTING.md) file, so it wasn't a simple merge. On top of it, releasing the package, along with all the documentation website and supporting materials is right now a manual process since I ran out of OSS credits for TravisCI, and have no time to re-implement fully automated CI on Github Actions.

Bumping a version takes me 2+ hours of manual work, which is the time that I don't spend with my family, or time that I don't spend with my dog, or time that I don't spend playing guitar. You get the point 😁

I am grateful to the active members of the community who still submit PRs, since this speeds up the process tremendously. You have to bear with me on this, however, as I'm maintaining this in my free time out of sheer good will.

I hope you all have a wonderful Thanksgiving! I'll release the `13.x.y` version tomorrow. In the meantime, cheers to y'all 🍻
