### ISSUE TITLE
ERROR for site owner: Invalid site key

### ISSUE THREAD

**Issue by lanzosuarez** [DethAriel/ng-recaptcha#62]
I just followed the installation steps then plug it in my view. And it show this error:" ERROR for site owner: Invalid site key"

**Comment by DethAriel** [comment]
Hi! Most likely the issue consists in exactly what the error message says - your site key is invalid. Check your reCAPTCHA admin account and ensure that you're not trying to use invisible recaptcha key for a regular recaptcha and vice-versa. 

Closing this, since this error is a support request for reCAPTCHA, which is outside the scope of this lib
