### ISSUE TITLE
Does not work under Proxy

### ISSUE THREAD

**Issue by robertop87** [DethAriel/ng-recaptcha#76]
### Summary

I have a implementation but it's not working under proxy, is there a fix or workaround for it?

**Comment by DethAriel** [comment]
Thx for reaching out, @robertop87! Unfortunately, this does not look like an issue with this library. If you feel like this is a mistake, feel free to reopen the issue, add as much details as possible, and create a reproducible example. Otherwise, try asking this on StackOverflow (or searching through [already asked questions](https://www.google.com/search?q=recaptcha+proxy+site%3Astackoverflow.com)) or reCAPTCHA google groups
